- name: Create 7D2D server directory
  file:
    path: "{{ server_dir }}"
    state: directory
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0755'

- name: Create 7D2D saves directory
  file:
    path: "{{ server_saves_dir }}"
    state: directory
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0755'

- name: Install 7 Days to Die server using SteamCMD
  shell: >
    sudo -u steam
    {{ steamcmd_dir }}/steamcmd.sh
    +force_install_dir {{ server_dir }}
    +login anonymous
    +app_update 294420 validate
    +quit
  args:
    chdir: "{{ steamcmd_dir }}"

- name: Ensure steamcmd user owns the entire 7D2D server directory
  file:
    path: "{{ server_dir }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    recurse: yes

- name: Backup original serverconfig.xml
  copy:
    src: "{{ server_config }}"
    remote_src: yes
    dest: "{{ server_config }}.bak"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0644'

- name: Copy serverconfig.xml
  copy:
    src: "serverconfig.xml"
    dest: "{{ server_config }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0644'
  notify: Handle service state

- name: Backup original serveradmin.xml
  copy:
    src: "{{ server_admin }}"
    remote_src: yes
    dest: "{{ server_admin }}.bak"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0644'

- name: Copy serveradmin.xml
  copy:
    src: "serveradmin.xml"
    dest: "{{ server_admin }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0644'
  notify: Handle service state

- name: Check if unit file existed before
  stat:
    path: "/etc/systemd/system/{{ server_service }}"
  register: service_file

- name: Ensure systemd service file is present
  template:
    src: "{{ server_service }}.j2"
    dest: "/etc/systemd/system/{{ server_service }}"
    owner: root
    group: root
    mode: '0644'
  notify: Handle service state
