- name: Check if unit file existed before
  stat:
    path: "/etc/systemd/system/{{ service_name }}.service"
  register: service_file

- name: Ensure systemd service file is present
  template:
    src: "{{ service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: Handle service state

- name: Ensure systemd env file is present
  template:
    src: "{{ service_name }}.env.j2"
    dest: "/etc/{{ service_name }}.env"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0644'
  notify: Handle service state
