- name: Install zsh
  package:
    name:
      - zsh
      - git
    state: present
  become: true
  tags: zsh

- name: Set user shell to zsh
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  become: true
  loop:
    - "{{ os_user }}"
    - root
  tags: zsh

- name: Install Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
  become: true
  become_user: "{{ item }}"
  loop:
    - "{{ os_user }}"
    - root
  tags: zsh
 
- name: Install zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
  become: true
  become_user: "{{ item }}"
  loop:
    - "{{ os_user }}"
    - root
  tags: zsh

- name: Copy .zshrc file
  copy:
    src: files/.zshrc
    dest: ~/.zshrc
  become: true
  become_user: "{{ item }}"
  loop:
    - "{{ os_user }}"
    - root
  tags: zsh
